CREATE TABLE IF NOT EXISTS admin_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Remove all existing admin users (optional, for reset)
TRUNCATE TABLE admin_users;

-- Insert default admin account (username: admin, password: admin123)
-- Replace the hash below with one generated by your PHP server if needed
INSERT INTO admin_users (username, password)
VALUES ('admin', '$2y$10$P1YQ2LX6CfpnwxEFXxB9H.2RSFvPtJIBF9F0QuH95eroMVXQH3cDa');
