USE occ_enrollment;

DROP TABLE IF EXISTS pending_enrollments;
CREATE TABLE pending_enrollments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    verification_token VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    middlename VARCHAR(50),
    lrn VARCHAR(20) NOT NULL,
    address TEXT NOT NULL,
    gender CHAR(1) NOT NULL,
    date_of_birth DATE NOT NULL,
    age INT NOT NULL,
    civil_status VARCHAR(20) NOT NULL,
    contact_no VARCHAR(20) NOT NULL,
    last_school VARCHAR(100) NOT NULL,
    school_address TEXT NOT NULL,
    strand VARCHAR(50) NOT NULL,
    preferred_program VARCHAR(20) NOT NULL,
    is_working CHAR(1) NOT NULL DEFAULT 'N',
    employer VARCHAR(100),
    position VARCHAR(100),
    working_hours VARCHAR(50),
    preferred_schedule VARCHAR(20) NOT NULL,
    father_name VARCHAR(100) NOT NULL,
    father_occupation VARCHAR(100),
    father_education VARCHAR(50),
    father_contact VARCHAR(20),
    num_brothers INT DEFAULT 0,
    family_income DECIMAL(10,2) NOT NULL,
    mother_name VARCHAR(100) NOT NULL,
    mother_occupation VARCHAR(100),
    mother_education VARCHAR(50),
    mother_contact VARCHAR(20),
    num_sisters INT DEFAULT 0,
    guardian_name VARCHAR(100) NOT NULL,
    guardian_contact VARCHAR(20) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_expires TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
