USE occ_enrollment;

-- Create students table if it doesn't exist
CREATE TABLE IF NOT EXISTS students (
    student_id VARCHAR(20) PRIMARY KEY,
    user_id INT,
    lastname VARCHAR(50) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    middlename VARCHAR(50),
    course VARCHAR(10) NOT NULL,
    year_level INT NOT NULL,
    section VARCHAR(5) NOT NULL,
    current_semester INT NOT NULL,
    school_year VARCHAR(20) NOT NULL,
    units_earned INT NOT NULL DEFAULT 0,
    gpa DECIMAL(3,2),
    status VARCHAR(20) DEFAULT 'Regular',
    email VARCHAR(100) NOT NULL,
    lrn VARCHAR(20) NOT NULL,
    address TEXT NOT NULL,
    gender CHAR(1) NOT NULL,
    date_of_birth DATE NOT NULL,
    age INT NOT NULL,
    civil_status VARCHAR(20) NOT NULL,
    contact_no VARCHAR(20) NOT NULL,
    last_school VARCHAR(100) NOT NULL,
    school_address TEXT NOT NULL,
    strand VARCHAR(50) NOT NULL,
    preferred_program VARCHAR(20) NOT NULL,
    is_working CHAR(1) NOT NULL DEFAULT 'N',
    employer VARCHAR(100),
    position VARCHAR(100),
    working_hours VARCHAR(50),
    preferred_schedule VARCHAR(20) NOT NULL,
    father_name VARCHAR(100) NOT NULL,
    father_occupation VARCHAR(100),
    father_contact VARCHAR(20),
    num_brothers INT DEFAULT 0,
    family_income DECIMAL(10,2) NOT NULL,
    mother_name VARCHAR(100) NOT NULL,
    mother_occupation VARCHAR(100),
    mother_contact VARCHAR(20),
    num_sisters INT DEFAULT 0,
    guardian_name VARCHAR(100) NOT NULL,
    guardian_contact VARCHAR(20) NOT NULL,
    enrollment_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
